[versions]
#libraries
lombok = "1.18.42"

#plugins
kotlin = "2.2.21"
changelog = "2.4.0"
intelliJPlatform = "2.9.0"
detekt = "1.23.8"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }


[plugins]
# Kotlin support
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# gradle-changelog-plugin - read more: https://github.com/JetBrains/gradle-changelog-plugin
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
# gradle-intellij-plugin - read more: https://github.com/JetBrains/gradle-intellij-plugin
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
# detekt linter - read more: https://detekt.github.io/detekt/gradle.html
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
